#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: distutils3
# autospec version: v10
# autospec commit: 5905be9
#
Name     : pypi-pywbem
Version  : 1.7.0
Release  : 93
URL      : https://files.pythonhosted.org/packages/f9/fe/0aaa4b2fb22be99aebf15b2fba6da1460687dc037313ff6cf3d0828e5e7d/pywbem-1.7.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/f9/fe/0aaa4b2fb22be99aebf15b2fba6da1460687dc037313ff6cf3d0828e5e7d/pywbem-1.7.0.tar.gz
Summary  : pywbem - A WBEM client
Group    : Development/Tools
License  : Apache-2.0 LGPL-2.1
Requires: pypi-pywbem-bin = %{version}-%{release}
Requires: pypi-pywbem-license = %{version}-%{release}
Requires: pypi-pywbem-python = %{version}-%{release}
Requires: pypi-pywbem-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(idna)
BuildRequires : pypi(ply)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Pywbem - A WBEM client and related utilities, written in pure Python
[![Version on Pypi](https://img.shields.io/pypi/v/pywbem.svg)](https://pypi.python.org/pypi/pywbem/)
[![Test status (master)](https://github.com/pywbem/pywbem/actions/workflows/test.yml/badge.svg?branch=master)](https://github.com/pywbem/pywbem/actions/workflows/test.yml?query=branch%3Amaster)
[![Docs status (master)](https://readthedocs.org/projects/pywbem/badge/?version=latest)](https://readthedocs.org/projects/pywbem/builds/)
[![Test coverage (master)](https://coveralls.io/repos/github/pywbem/pywbem/badge.svg?branch=master)](https://coveralls.io/github/pywbem/pywbem?branch=master)
[![Supported Python](https://img.shields.io/pypi/pyversions/pywbem.svg?color=brightgreen)](https://pypi.python.org/pypi/pywbem/)

%package bin
Summary: bin components for the pypi-pywbem package.
Group: Binaries
Requires: pypi-pywbem-license = %{version}-%{release}

%description bin
bin components for the pypi-pywbem package.


%package license
Summary: license components for the pypi-pywbem package.
Group: Default

%description license
license components for the pypi-pywbem package.


%package python
Summary: python components for the pypi-pywbem package.
Group: Default
Requires: pypi-pywbem-python3 = %{version}-%{release}

%description python
python components for the pypi-pywbem package.


%package python3
Summary: python3 components for the pypi-pywbem package.
Group: Default
Requires: python3-core
Provides: pypi(pywbem)
Requires: pypi(certifi)
Requires: pypi(idna)
Requires: pypi(ply)
Requires: pypi(pyyaml)
Requires: pypi(requests)
Requires: pypi(setuptools)
Requires: pypi(six)
Requires: pypi(urllib3)
Requires: pypi(yamlloader)

%description python3
python3 components for the pypi-pywbem package.


%prep
%setup -q -n pywbem-1.7.0
cd %{_builddir}/pywbem-1.7.0
pushd ..
cp -a pywbem-1.7.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1713285005
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
pypi-dep-fix.py . urllib3
python3 setup.py build

pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
pypi-dep-fix.py . urllib3
python3 setup.py build

popd
%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pywbem
cp %{_builddir}/pywbem-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-pywbem/caeb68c46fa36651acf592771d09de7937926bb3 || :
cp %{_builddir}/pywbem-%{version}/pywbem/_vendor/nocasedict/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pywbem/b386b371ce94933e63ced1052aa72a60da5485ff || :
cp %{_builddir}/pywbem-%{version}/pywbem/_vendor/nocaselist/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pywbem/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
python3 -tt setup.py build  install --root=%{buildroot}
pypi-dep-fix.py %{buildroot} urllib3
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mof_compiler
/usr/bin/mof_compiler.bat

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pywbem/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/pypi-pywbem/b386b371ce94933e63ced1052aa72a60da5485ff
/usr/share/package-licenses/pypi-pywbem/caeb68c46fa36651acf592771d09de7937926bb3

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
